### ISSUE TITLE
playlist broken

### ISSUE THREAD

**Issue by banther7** [YePpHa/YouTubeCenter#1323]
when ever i watch a video with a playlist it only shows the top part of it and none of the videos show up. here a example shot: ![Puush](http://puu.sh/dCRju/ec4faa3c0f.png)

**Comment by ReporterX** [comment]
Install Stylish addon.
Go to youtube.com
Write new style -> For youtube.com...
Copy this code:
```css
.playlist-videos-list {
    height: 260px !important;
    overflow: auto !important;
}
```
Name the style. Save.

With this style fix, you can scroll properly on the playlist.
