### ISSUE TITLE
Playlist window missing

### ISSUE THREAD

**Issue by kilara1988** [YePpHa/YouTubeCenter#1345]
When you play a playlist the window on the right(right of the video window) should show the playlist with the other videos in it.Right now that list is missing.Tested with both HTML5 and flash player with same results.Works fine when YTC is disabled.Running latest Nightly + GM + latest dev script.
![untitled](https://cloud.githubusercontent.com/assets/1025376/5606366/8d856d4e-9434-11e4-835e-948a0738998e.png)

**Comment by ReporterX** [comment]
**Temporary fix**

Install Stylish addon.
Go to youtube.com
Write new style -> For youtube.com...
Copy this code:
```css
.playlist-videos-list {
    height: 260px !important;
    overflow: auto !important;
}
```
Name the style. Save.

With this style fix, you can get back the playlist with scrollbar, and you can scroll properly on the playlist.
