### ISSUE TITLE
How to hide the empty space?

### ISSUE THREAD

**Issue by Turbonator** [YePpHa/YouTubeCenter#1517]
![image](https://cloud.githubusercontent.com/assets/11126118/6423773/bc99a69c-bef3-11e4-951f-4a2d8349d6bb.png)

If you hide the Footer it leaves this kinda big empty space behind bottom of the website. I try to tweak the YouTube window size to hide it with Stylish without luck. Please help.

If you use Inspect Element you notice that there's .padding-bottom 191px on .body-container which causes this, if you untick the .padding-bottom then this empty space goes away. Or if you untick height auto; on .body-container then the height goes to 955px which also fixes the empty space.

**Comment by Yonezpt** [comment]
If you reduce/remove that blank space at the bottom it will cause problems with loading images once you scroll down the page, you will constantly reach the end of pages and lots of images will not show up.

**Comment by Turbonator** [comment]
But I asked how to hide it, not what it might cause.

**Comment by Yonezpt** [comment]
If you use Stylish you can set the rule you mentioned just the way you tested.
In this case, according to the details you provided, the rule you will need is 
````css
.body-container{
    padding-bottom:none !important;
}
````

**Comment by Turbonator** [comment]
Not working.

**Comment by Yonezpt** [comment]
That's because the element identification you want to change is not a class, but an id so `.body-container` needs to change to `#body-container` and `padding-bottom` needs to change from `none` to `0`, so:

````css
#body-container{
    padding-bottom:0 !important;
}
````

**Comment by Turbonator** [comment]
Works. Now can I also ask how to hide these inside the red box: (Kinda related to the topic sorry)

![untitled](https://cloud.githubusercontent.com/assets/11126118/6424375/98c8b0d4-bf00-11e4-9ee0-dafff919703d.png)

**Comment by Yonezpt** [comment]
````css
.branded-page-v2-top-row{
display:none !important;
}
````
But a warning; you will lose channel navigation capabilities and it is possible that the page might scroll down by itself when you open the channel page.

**Comment by Turbonator** [comment]
Not working.

**Comment by Yonezpt** [comment]
I have tested it and it is working. Make sure you do not have any error or another rule causing conflict.

**Comment by Turbonator** [comment]
I tested this on https://www.youtube.com/user/theRadBrad/videos and not working.

**Comment by Yonezpt** [comment]
So did I and it is working. Try disabling any other addon and any other style to see if there is anything causing it to fail. There is nothing else I can think of.

**Comment by Turbonator** [comment]
Looks like YouTube Center is causing it.

**Comment by Yonezpt** [comment]
Now it should work
````css
html body#body div#page div.branded-page-v2-top-row{
    display:none !important;
}
````

**Comment by Turbonator** [comment]
It left one bar behind:

![image](https://cloud.githubusercontent.com/assets/11126118/6424723/09984e9e-bf0d-11e4-85ec-421e801f228a.png)

**Comment by Yonezpt** [comment]
````css
html body#body div#page div.branded-page-v2-top-row, #masthead-appbar-container{
    display:none !important;
}
````
