### ISSUE TITLE
Player Overlaps Content

### ISSUE THREAD

**Issue by gangsthub** [YePpHa/YouTubeCenter#1786]
IDK if it's just Youtube ES (spain) or just for my custom player sizes, but this is what I wope up to:

![image](https://cloud.githubusercontent.com/assets/6775220/7553530/b5f950ac-f6fd-11e4-848d-713cf7c2ae2f.png)

These are my settings: http://pastebin.com/LEEEdCAF
UA: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36

**Comment by gangsthub** [comment]
This solved the problem for me:

```css
/* YoutubeCenter temporal fixes */

#placeholder-player .player-api {
    position:absolute;
}

#player-api {
    position:relative!important;
}
```

![image](https://cloud.githubusercontent.com/assets/6775220/7553535/3c4280ac-f6fe-11e4-8344-f8eca8dcc3f6.png)


Hope it helps.
