### ISSUE TITLE
[Feature Request] Transparent player should show the standard controls when not started

### ISSUE THREAD

**Issue by mleyen** [YePpHa/YouTubeCenter#1985]
I have just been forced to the new transparent player.

With the old player, when "prevent autoplay" and "prevent autoload" are enabled, it shows the standard controls (progress bar and volume bar) before the video is started, allowing you to view the progress bar preview before you start, or for that matter, to start anywhere you want.

The transparent player only shows the big play button. Is it possible to have the old behavior with the new player?

Also, is there an option I missed in YTC settings to force the old player?

**Comment by Trueffel** [comment]
I'd be interested too. This one is so ugly. I really dont understand why YT forces some of the things they do....

**Comment by snintendog** [comment]
Good to know that I'm not the only one who hates transparent/hidden controls.

**Comment by mleyen** [comment]
I started up Firebug and made up a fix for it.

If you have Stylish installed (or whatever is the Google Chrome equivalent), add this as a new style : 
```css
@namespace url(http://www.w3.org/1999/xhtml);

@-moz-document domain("youtube.com") {
.unstarted-mode .ytp-chrome-bottom,
.unstarted-mode .ytp-progress-bar-container,
.unstarted-mode .ytp-progress-bar {
display: block !important;
}

}
```

You also need some JavaScript using Greasemonkey.
```javascript
// ==UserScript==
// @id             www.youtube.com-8b0c2516-0e76-4ce6-bed9-4e461f1ba9f8@scriptish
// @name           YT remove aria-hidden
// @version        1.0
// @namespace      
// @author         
// @description    
// @include        http*://www.youtube.com/watch?*
// @run-at         document-end
// ==/UserScript==

var controls = document.getElementsByClassName('ytp-chrome-bottom')[0];

controls.removeAttribute('aria-hidden');
```
I don't know how to upload Greasemonkey files, so you'll have to copy and install it manually.
