### ISSUE TITLE
Channel icons in grid layout

### ISSUE THREAD

**Issue by jonnyrobbie** [YePpHa/YouTubeCenter#995]
Is it possible to include a channel icon (thumbnail) in the grid layout (like it is in the normal view)?
I like the grid layout because of its condensed style, but it would be better if videos were distinguished by more than just a simple text version of channel name (which is easily overlooked), but also by its channel icon.
I can do it with stylish and:

``` css
    @namespace url(http://www.w3.org/1999/xhtml);
    @-moz-document domain("www.youtube.com") {
    .ytcenter-gridview #browse-items-primary .branded-page-module-title {
      display: inherit;
        }
        .ytcenter-gridview .ytcenter-grid-subscriptions-username {
            display: none;
        }
    }
```

but it would be nice if it could be done natively.
Thanks
